# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-23 16:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_user_alias'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='alias',
        ),
        migrations.AddField(
            model_name='user',
            name='birthday',
            field=models.DateField(default=datetime.datetime(2018, 3, 23, 11, 28, 3, 344000)),
        ),
    ]
