# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-23 17:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_auto_20180323_1129'),
        ('quotes', '0002_auto_20180323_1209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='quotes',
        ),
        migrations.RemoveField(
            model_name='list',
            name='user',
        ),
        migrations.AddField(
            model_name='quote',
            name='favoritedby',
            field=models.ManyToManyField(related_name='favquotes', to='registration.User'),
        ),
        migrations.AddField(
            model_name='quote',
            name='text',
            field=models.TextField(default='Placeholder'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='List',
        ),
    ]
